### PR TITLE
AVIF post

### PR DESCRIPTION
**Pull request by jakearchibald**
TODOs from feedback:

- [x] AVIF is "royalty free" rather than simply "open"
- [x] The accept header is used to detect image support on the server, not client hints (quite embarrassed I made that mistake)
- [x] Briefly cover how I create the images, and the inherent bias in that.
- [x] Mention that the F1 image was difficult to compress as JPEG. At lower settings, obvious banding is introduced. As a result, the JPEG version is actually higher quality than the WebP & AVIF (note the detail around the car mirror in particular).
- [x] Pivot the 'similar file size' tests as being more than just 'for fun'.
- [x] The AVIF smoothing is an artefact - talk a little about how these artefacts are less visually abrasive than JPEG artefacts.
- [x] Mention edge detection in AVIF https://jmvalin.ca/daala/paint_demo/
- [x] "It isn't impossible to have a top-to-bottom render" - correct weird double negative
- [x] NVidia announced 30xx cards have AV1 hw decode.
- [x] A little section on how the blog post and demo was made (using Squoosh decoders)
- [x] There's a race condition in my image decoder, related to switching between img and canvas. Switch things around so the intersection observer is always used, and `img.decode()` is used to time the switch of the image. This should also solve the flash of white when switching between canvas and image.
- [x] "At the same size" is a crap heading. Use something better.
- [x] The white gap introduced by the loading video looks bad. Screen capture it against a different background?

### CODE REVIEW

**Comment by kornelski** [comment]
For the first comparison I suggest using this image: f166kb

and for the small file comparison, it'd be best to show that JPEG has both worst file size and worst quality *at the same time*: 22kbjpeg

**Comment by jakearchibald** [comment]
@kornelski yeah, that first F1 image is acceptable and smaller than the one I used. Cheers! What settings did you use? I struggled to get around that size without seeing patches of purple appearing on the road, or general blockiness.

With the second image, the one I already have in the post is closer to the AVIF size, so what's the benefit of changing it to the one above?

Also, are you happy for me to acknowledge your help here, or do you want your name to stay out of it?

**Comment by jakearchibald** [comment]
@kornelski I've also come up with a set of TODOs from your other feedback https://github.com/jakearchibald/jakearchibald.com/pull/6#issue-478644603

**Comment by kornelski** [comment]
@jakearchibald oh, I'd suggest to make the AVIF one closer to 22KB, so that all three have about WebP's size.

**Comment by kornelski** [comment]
For these images I've used the magic of MozJPEG settings, which let you choose quantization tables, so you can choose posterization vs sharpness trade-off.

**Comment by jakearchibald** [comment]
Nice, I didn't do that. Was it one of the preset tables, or did you make your own?

**Comment by jakearchibald** [comment]
@kornelski https://deploy-preview-6--focused-booth-abbed1.netlify.app/2020/avif-is-exciting/#technique - I've added a section here clarifying the 'technique', and the biases it creates. I also used your version of the F1 image, and draw attention to the extra detail that the JPEG has.

**Comment by turystahobby** [comment]
avif rules

**Pull request merged**
